Add try-catch around websocket accept (#2154)
This kind of uncaught exceptions happen occasionally, which crashes the
node. Googling for the EPIPE error reveals that this is apparently due
to trying to write to a socket which is already closed. However, this
stack trace reveals it happens on accepting an incoming connection to
the websocket server, so something's wrong with the connection
immediately upon establishment.

```
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
    at handleWriteReq (node:internal/stream_base_commons:63:21)
    at writeGeneric (node:internal/stream_base_commons:149:15)
    at TLSSocket.Socket._writeGeneric (node:net:931:11)
    at TLSSocket.Socket._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at TLSSocket.Writable.write (node:internal/streams/writable:337:10)
    at WebSocketRequest.accept (/opt/network/node_modules/websocket/lib/WebSocketRequest.js:458:21)
    at WebSocketServer.<anonymous> (/opt/network/packages/dht/src/connection/websocket/WebsocketServer.ts:108:48) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```