docs(client): Remove duplicate document generation (#2556)
Before this PR we had two different API reference pages:
- https://docs.streamr.network/usage/sdk/api/ (up-to-date, updated with
Docusaurus)
- https://api-docs.streamr.network/ (deprecated, manually generated,
still in Brubeck era)

In this PR the use of deprecated API reference page was removed.

## Changes

- Updated the [README](https://www.npmjs.com/package/@streamr/sdk) link
to the API reference
- Removed the deprecated release step
- Removed the deprecated API documentation generation script in `client`
package
- Removed the deprecated CI step which runs `npm run docs` to check that
the API documentation doesn't contain broken links, see Future
improvements


## Other

Also upgraded TypeScript version used by Docusaurus. This was done to
avoid the following error in document generation:
```
npm ci && npm run build
../node_modules/@tsconfig/node18/tsconfig.json:7:13 - error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'es2020', 'es2021', 'es2022', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'webworker.iterable', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asyncgenerator', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.object', 'es2019.string', 'es2019.symbol', 'es2019.intl', 'es2020.bigint', 'es2020.date', 'es2020.promise', 'es2020.sharedmemory', 'es2020.string', 'es2020.symbol.wellknown', 'es2020.intl', 'es2020.number', 'es2021.promise', 'es2021.string', 'es2021.weakref', 'es2021.intl', 'es2022.array', 'es2022.error', 'es2022.intl', 'es2022.object', 'es2022.sharedmemory', 'es2022.string', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint', 'esnext.string', 'esnext.promise', 'esnext.weakref'.
7     "lib": ["es2023"],
              ~~~~~~~~
[error] Documentation could not be generated due to the errors above.
```

## Future improvements

- The `npm run docs` task run by CI checked that all
classes/interfaces/etc. were exported correctly. We should configure
Docusaurus to throw an error in such classes.