fix(network): flaky tests (#497)
I was unable to replicate the flakiness locally, my best guess is that the "full" tracker is somehow sending messages in the middle of the test when we see the flakiness. Thus I thought it is a good idea to stop the "full" tracker before the tests are executed.

Original flaky test:
```
Electron 13.6.7 (Node 14.16.0): Executed 252 of 252 (1 FAILED) (1 min 18.121 secs / 1 min 17.443 secs)
TOTAL: 1 FAILED, 251 SUCCESS


1) sendRtcConnect is delivered (trackerServer->nodeToTracker)
     delivery of messages in protocol layer
     Error: expect(received).toEqual(expected) // deep equality

Expected: "trackerServer"
Received: "477563ee-5795-4778-a137-bb3182bdb5e6"
error properties: Object({ matcherResult: Object({ actual: '477563ee-5795-4778-a137-bb3182bdb5e6', expected: 'trackerServer', message: 'expect(received).toEqual(expected) // deep equality
Expected: "trackerServer"
Received: "477563ee-5795-4778-a137-bb3182bdb5e6"', name: 'toEqual', pass: false }) })
Error: expect(received).toEqual(expected) // deep equality
Expected: "trackerServer"
Received: "477563ee-5795-4778-a137-bb3182bdb5e6"
    at dist/commons.js:143701:24
    at Generator.next (<anonymous>)
    at fulfilled (dist/commons.js:143526:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

```