test(node): Fix `MaintainTopologyService` test variable shadowning (#2936)
Fixed a variable shadowing issues in `MaintainTopologyService.test.ts`.
The test state variable `operatorFleetState ` wasn't used because it was
shadowed by a local variable.

Also removed optional chaining. The optional chaining hide this
shadowing issue, i.e. better to not to use optional chaining so that
test would fail without the fix.

This is a blocker to https://github.com/streamr-dev/network/pull/2936.
In TypeScript v5.7 the `npm run check` errors like:
```
Error: test/integration/plugins/operator/MaintainTopologyService.test.ts(64,15): error TS2454: Variable 'operatorFleetState' is used before being assigned.
```