Update to Node 20 (#2271)
## Summary

Node.js active LTS release is now v20. Previous LTS v18 is now in
maintenance period. See https://nodejs.org/en/about/previous-releases

## Misc changes
Remove property `notification` (apparently a re-declaration?) from
DhtCallContext.ts due to error
```
Error: ../dht/src/rpc-protocol/DhtCallContext.ts(9,5): error TS2612: Property 'notification' will overwrite the base property in 'ProtoCallContext'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
```