deps: Typescript v4.9 (#1028)
Updated TypeScript to v4.9 and `@typescript-eslint` to v5.46.0.

Small change to `packages/client/src/utils/iterators.ts:145:24` was needed as the build failed with new TypeScript version:
- `error TS2638: Type 'Cancelable<T> | NonNullable<T>' may represent a primitive value, which is not permitted as the right operand of the 'in' operator.`