chore(docs): [DREL-250] Smoke test for API docs (#2934)
Added additional check for `test-docs` CI job. It checks whether the
`docs/usage/sdk/api` directory exists. It it doesn't, TypeDoc most
likely failed and the whole API docs section is missing.

## Example

CI output when [test
fails](https://github.com/streamr-dev/network/actions/runs/12236169946/job/34129034071?pr=2929):
```
Run ./api-docs-smoke-test.sh
No files in "docs/usage/sdk/api" directory. Maybe TypeDoc failed?
Error: Process completed with exit code 1.
```