broker [NET-384]: did one regex do it? (#133)
Currently the config requires the ethereumPrivateKey to have the 0x prefix, although this is not customary in the Ethereum space. Versions with and without the prefix should be accepted.

Currently, when attempting to give a private key without the prefix, the following error is printed:

Error: /ethereumPrivateKey must match pattern "^0x[a-f0-9]{64}$"