update to TS 5.3 (#2274)
## Summary

Upgrade to TS 5.3

## Changes

- Why change b55cbe7? Due to error
> Error: ../client/src/encryption/RSAKeyPair.ts(20,5): error TS2322:
Type 'import("crypto").webcrypto.SubtleCrypto' is not assignable to type
'SubtleCrypto'.
  Types of property 'generateKey' are incompatible.
Type '{ (algorithm: RsaHashedKeyGenParams | EcKeyGenParams, extractable:
boolean, keyUsages: readonly KeyUsage[]): Promise<CryptoKeyPair>;
(algorithm: Pbkdf2Params | ... 1 more ... | HmacKeyGenParams,
extractable: boolean, keyUsages: readonly KeyUsage[]): Promise<...>;
(algorithm: AlgorithmIdentifier, extractable: boolean...' is not
assignable to type '{ (algorithm: "Ed25519", extractable: boolean,
keyUsages: readonly ("sign" | "verify")[]): Promise<CryptoKeyPair>;
(algorithm: RsaHashedKeyGenParams | EcKeyGenParams, extractable:
boolean, keyUsages: readonly KeyUsage[]): Promise<...>; (algorithm:
Pbkdf2Params | ... 1 more ... | HmacKeyGenParams, extractable:
boolea...'.
      Types of parameters 'algorithm' and 'algorithm' are incompatible.
Type 'string' is not assignable to type 'RsaHashedKeyGenParams |
EcKeyGenParams'.
---------

Co-authored-by: Teo Gebhard <teo@streamr.com>