ci: multiple tags issue in Docker build (#1172)
### Error

Docker builds jobs fail if there were multiple tags pointing to `HEAD`:
```
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'client/v8.2.0'
```

### Changes

Now we collect only Broker-release tags (`broker/v*`) to the environment variable. We can safely ignore other tags because the Docker meta task uses only tags which match that same pattern (line 76).