feat(network): Remove bin scripts (#1029)
Removed all scripts from `network`'s `bin` directory. The scripts aren't currently runnable, because the imports have not been updated (e.g. `Error: Cannot find module '../dist/src/helpers/Logger'`).

The scripts have been used for manual testing.  The error implies that there has not been use for these scripts for few months (at least not after https://github.com/streamr-dev/network/pull/746 where imports changed).

We have good integration tests in `network` package, and therefore we don't most likely need these scripts. Similar manual testing can also be done with `cli-tools` if needed.