chore(DHT): WS library client for NodeJS websocket client connections (#2384)
## Summary

Use the ws library to open client ws connections in NodeJS. `websocket`
library is still used in browsers to avoid compatibility issues with
between different browsers WebSocket implementations.

This change improves the CPU use in NodeJS

Should fix this funky error in client e2e tests:
```
Test suite failed to run
    TypeError: require(...) is not a function
      at Object.createBufferingLogger [as BufferingLogger] (../../node_modules/websocket/lib/utils.js:24:39)
      at new WebSocketConnection (../../node_modules/websocket/lib/WebSocketConnection.js:42:25)
      at WebSocketClient.Object.<anonymous>.WebSocketClient.succeedHandshake (../../node_modules/websocket/lib/WebSocketClient.js:343:22)
      at WebSocketClient.Object.<anonymous>.WebSocketClient.validateHandshake (../../node_modules/websocket/lib/WebSocketClient.js:332:10)
      at ClientRequest.handleRequestUpgrade (../../node_modules/websocket/lib/WebSocketClient.js:2[61](https://github.com/streamr-dev/network/actions/runs/7972200333/job/21763492753?pr=2383#step:8:62):14)
```

## Other changes

- Renamed `ClientWebsocket` -> `WebsocketClientConnection`
(BrowserWebsocketClientConnection for browsers)