refactor(client): Throw `StreamrClientError` if storage node fetch fails (#1514)
If there is a HTTP fetch error when we fetch data from a storage node, the client throws an error with code `STORAGE_NODE_ERROR`. E.g. 
```
StreamrClientError: Storage node fetch failed: Query parameter "count" not a number: foobar2, httpStatus=400, url=...
StreamrClientError: Storage node fetch failed, httpStatus=500, url=...
```

Before this PR we threw a custom error instead of `StreamrClientError`. The previous implementation of HTTP error handling in `Resends#fetchStream` was not up-to-date: it tried to parse error codes from some other format than what current storage nodes produce.