Use `isolatedModules` (#3104)
## Summary 

- added `"isolatedModules": true` setting to `tsconfig.json` files
- changed type-exports to use `type` modified in export statements
- changed some imports of decorated signatures to use `type` modifier

## Problem

Before these change we got this warning when running tests:
```
ts-jest[ts-compiler] (WARN) Using hybrid module kind (Node16/18/Next) is only supported in "isolatedModules: true". Please set "isolatedModules: true" in your tsconfig.json.
```

(The error was printed only if some files were changed as `jest` caches
file transformations)

The warnings started after PR
https://github.com/streamr-dev/network/pull/3068. That PR upgraded
`ts-jest` from v29.2.6 to v29.3.1 (see
https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md).

## Related changes

When isolated modules are used, the type-exports must use `type`
modifier. The `npm run check` errors like this if those are not used:
```
Error: src/exports.ts(129,10): error TS1205: Re-exporting a type when 'isolatedModules' is enabled requires using 'export type'.
```

Autofixed the exports using this command:
```bash
npm run eslint --workspaces --if-present -- --fix --rule " '@typescript-eslint/consistent-type-exports': ['error', {
    fixMixedExportsWithInlineTypeSpecifier: true
}]"
```

Also the imports of decorated signatures (the
`@inject(ConfigInjectionToken) config: StrictStreamrClientConfig`
constructor parameters) needed the `type` modifier. The `npm run check`
errors like this if those are not used:
```
Error: src/publish/Publisher.ts(66,47): error TS1272: A type referenced in a decorated signature must be imported with 'import type' or a namespace import when 'isolatedModules' and 'emitDecoratorMetadata' are enabled.
```

## Other changes

Also removed obsolete `eslint-ignore` from` signingUtils.ts`.