feat(trackerless-network): Log exit event (#2366)
Log the error if the software crashes because of `uncaughtException` or `unhandledRejection`. Also send status code `1` to the operating system in those cases.

## Example

```ts
ERROR [2024-02-12T15:05:15.123] (NetworkStack             ): exit event: unhandledRejection
    err: {
      "type": "TypeError",
      "message": "Cannot read properties of undefined (reading 'metricsContext')",
      "stack":
          TypeError: Cannot read properties of undefined (reading 'metricsContext')
              at new NetworkStack (/Users/teogeb/workspace/network/packages/trackerless-network/dist/src/NetworkStack.js:47:39)
              at Immediate.<anonymous> (/Users/teogeb/workspace/network/packages/trackerless-network/dist/src/dev-sandbox.js:9:23)
    }
```

## Open questions 

Would it make sense to log info about other events (`SIGINT`, `SIGUSR1`, ...)? If we do that, we should avoid logging the multiple events: e.g. NodeJS always emits a separate `exit` event after `unhandledRejection`.