test(trackerless-network): Use `toEqualBinary()` custom matcher (#2806)
The `tsconfig.json` was added because without the file there were these
kinds of errors e.g. when `trackerless-network` unit tests were run:
```
ts-jest[config] (WARN) message TS151001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
...
src/logic/ContentDeliveryManager.ts:128:66 - error TS2339: Property 'contentMessage' does not exist on type '{ oneofKind: "contentMessage"; contentMessage: ContentMessage; } | { oneofKind: undefined; }'.
      Property 'contentMessage' does not exist on type '{ oneofKind: undefined; }'.
...
src/NetworkStack.ts:12:47 - error TS2732: Cannot find module '../package.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
``` 

## Future improvements

- Maybe we could tweak some configuration so that the `tsconfig.json`
file is not needed? The root level `jest.config.js` already defines that
`tsconfig.jest.json` should be used.